---
# Playbook 1 Configure Access Point on planned location on Cisco Catalyst Center
- name: Configure Access Point on planned location on Cisco Catalyst Center
  hosts: localhost
  connection: local
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Create access point location on Cisco Catalyst Center
      cisco.dnac.accesspoint_location_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged  # Options: merged, deleted
        config:  # Minimum 1; Maximum 100 config hierarchy
          - floor_site_hierarchy: "Global/USA/California/SAN JOSE/BLD24/Floor3"
            access_points:
              - accesspoint_name: IAC-TB4-SJ-AP1
                action: assign_planned  # Optional assign_planned, delete_position
                mac_address: 54:8a:ba:22:eb:c0  # Optional
                accesspoint_model: CW9172H
                position:
                  x_position: 30  # x-axis: from 0 to 100
                  y_position: 20  # y-axis: from 0 to 88
                  z_position: 8  # height: from 3.0 to 10
                radios:  # Minimum Items: 1; Maximum Items: 4
                  - bands: 2.4GHz  # can be 5Ghz and 6GHz
                    channel: 10
                    tx_power: 5  # Decibel milliwatts (dBm)
                    antenna:
                      antenna_name: Internal-CW9172H-x-2.4GHz
                      azimuth: 20  # support upto 360
                      elevation: 30  # support -90 upto 90
                  - bands: 5GHz  # can be 5Ghz and 6GHz
                    channel: 44
                    tx_power: 6  # Decibel milliwatts (dBm)
                    antenna:
                      antenna_name: Internal-CW9172H-x-5GHz
                      azimuth: 10  # support upto 360
                      elevation: 30  # support -90 upto 90

      register: output_list
