---
# Playbook 1 Configure Access Point on planned location on Cisco Catalyst Center
- name: Configure Access Point on planned location on Cisco Catalyst Center
  hosts: localhost
  connection: local
  vars_files:
    - "credentials.yml"
  tasks:
    - name: Create access point location on Cisco Catalyst Center
      cisco.dnac.accesspoint_location_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:  # Minimum 1; Maximum 100 config hierarchy
          - floor_site_hierarchy: "Global/USA/San Francisco/BGL_18/Test_Floor6"
            - accesspoint_name: main_wifi
              mac_address: a4:b2:39:5b:9c:00 # Optional
              serial_number: 9080V0I41J3 # Optional
              accesspoint_model: AP1310
              position:
                x_position: 100  # x-axis: from 0 to 100
                y_position: 200  # y-axis: from 0 to 88
                z_position: 300  # height: from 3.0 to 10
              radios:  # Minimum Items: 1; Maximum Items: 4
                - bands: 2.4GHz  # can be 5Ghz and 6GHz
                  channel: 6
                  tx_power: 5  # Decibel milliwatts (dBm)
                  antenna:
                    antenna_name: C-ANT9104-2.4GHz
                    azimuth: 1  # support upto 360
                    elevation: 30  # support -90 upto 90
                - bands: 5GHz  # can be 5Ghz and 6GHz
                  channel: 6
                  tx_power: 5  # Decibel milliwatts (dBm)
                  antenna:
                    antenna_name: AIR-ANT5135D-R
                    azimuth: 1  # support upto 360
                    elevation: 30  # support -90 upto 90

      register: output_list
