---
- name: Configure device credentials on Cisco Catalyst Center
  hosts: localhost
  vars_files:
    - "credentials.yml"
  connection: local
  gather_facts: false
  tasks:
    - name: Create application policy
      cisco.dnac.wireless_design_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: deleted
        config:
          - dot11ax_configuration:
              - design_name: "dot11ax_24ghz_design"
                feature_attributes:
                  radio_band: "2_4GHZ"
                  bss_color: true
                  target_waketime_broadcast: true
                  non_srg_obss_pd_max_threshold: -62
                  target_wake_up_time_11ax: true
                  obss_pd: true
                unlocked_attributes:
                  # - "radio_band"
                  # - "bss_color"
                  # - "target_waketime_broadcast"
                  # - "non_srg_obss_pd_max_threshold"
                  # - "target_wake_up_time_11ax"
                  # - "obss_pd"

              # - design_name: "dot11ax_5ghz_design"
              #   feature_attributes:
              #     radio_band: "5GHZ"
              #     bss_color: true
              #     target_waketime_broadcast: true
              #     non_srg_obss_pd_max_threshold: -75
              #     target_wake_up_time_11ax: true
              #     obss_pd: true
              #   unlocked_attributes:
              #     - "radio_band"
              #     - "bss_color"
              #     - "target_waketime_broadcast"
              #     - "non_srg_obss_pd_max_threshold"
              #     - "target_wake_up_time_11ax"
              #     - "obss_pd"

              # - design_name: "dot11ax_6ghz_design"
              #   feature_attributes:
              #     radio_band: "6GHZ"
              #     bss_color: true
              #     target_waketime_broadcast: true
              #     multiple_bssid: true
              #     target_wake_up_time_11ax: true
              #   unlocked_attributes:
              #     - "radio_band"
              #     - "bss_color"
              #     - "target_waketime_broadcast"
              #     - "multiple_bssid"
              #     - "target_wake_up_time_11ax"



