---
- name: Configure device credentials on Cisco Catalyst Center
  hosts: localhost
  vars_files:
    - "credentials.yml"
  connection: local
  gather_facts: false
  tasks:
    - name: Create application policy
      cisco.dnac.wireless_design_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: merged
        config:
          - advanced_ssid:
              - design_name: ""
                feature_attributes:
                  peer2peer_blocking: "DISABLE"  #enum : DROP, FORWARD_UP, ALLOW_PVT_GROUP, DISABLE
                  passive_client: false
                  prediction_optimization: false
                  dual_band_neighbor_list: false
                  radius_nac_state: true
                  dhcp_required: true
                  dhcp_server: "10.10.10.5"
                  flex_local_auth: false
                  target_wakeup_time: true
                  downlink_ofdma: true
                  uplink_ofdma: true
                  downlink_mu_mimo: true
                  uplink_mu_mimo: true
                  dot11ax: true
                  aironet_ie_support: true
                  load_balancing: false
                  dtim_period_5ghz: 2  # 1 -255
                  dtim_period_24ghz: 2 # 1 -255
                  scan_defer_time: 100 
                  max_clients: 200  
                  # For physical 9800 series controllers
                  # [0-5000] - 9800-L series
                  # [0-32000] - 9800-40 series
                  # [0-64000] - 9800-80 series

                  # 9800-80 series For 9800-CL series controllers
                  # [0-10000] Small (S) VM 
                  # 0-32000]  Medium (M) VM
                  # [0-64000] Large (L) VM

                  # For Embedded Wireless Controller and Mobility Express - [0-2000]9300 platform.
                  # 9300 platform - [0-4000]
                  # AireOS platform[0-3000]
                  # 3500 series - [0-3000]
                  #  5500 series - [0-20000]
                  # 8500 series - [0 - 64000]

                  max_clients_per_radio: 100 #0 to 500
                  max_clients_per_ap: 300  # 0 to 1200
                  wmm_policy: "ALLOWED" #DISABLED, REQUIRED, ALLOWED
                  multicast_buffer: true 
                  multicast_buffer_value: 50 
                  media_stream_multicast_direct: true
                  mu_mimo_11ac: true
                  wifi_to_cellular_steering: false
                  wifi_alliance_agile_multiband: false
                  fastlane_asr: false
                  dot11v_bss_max_idle_protected: false
                  universal_ap_admin: false
                  opportunistic_key_caching: false
                  ip_source_guard: false
                  dhcp_opt82_remote_id_sub_option: false
                  vlan_central_switching: false
                  call_snooping: false
                  send_disassociate: false
                  sent_486_busy: false
                  ip_mac_binding: false
                  idle_threshold: 300 #
                  defer_priority_0: false
                  defer_priority_1: false
                  defer_priority_2: false
                  defer_priority_3: false
                  defer_priority_4: false
                  defer_priority_5: false
                  defer_priority_6: false
                  defer_priority_7: false
                  share_data_with_client: false
                  advertise_support: false
                  advertise_pc_analytics_support: false
                  send_beacon_on_association: false
                  send_beacon_on_roam: false
                  fast_transition_reassociation_timeout: 200 
                  mdns_mode: "MDNS_SD_BRIDGING" #MDNS_SD_BRIDGING, MDNS_SD_DROP, MDNS_SD_GATEWAY
                unlocked_attributes:
                  # - "peer2peer_blocking"
                  # - "passive_client"
                  # - "dot11ax"
                  # - "load_balancing"
                  # - "max_clients"
                  # - "max_clients_per_radio"
                  # - "max_clients_per_ap"
                  # - "wmm_policy"
                  # - "dtim_period_5ghz"
                  # - "dtim_period_24ghz"
                  # - "scan_defer_time"
                  # - "mdns_mode"




