---
- name: Configure device credentials on Cisco Catalyst Center
  hosts: localhost
  vars_files:
    - "credentials.yml"
  connection: local
  gather_facts: false
  tasks:
    - name: Create application policy
      cisco.dnac.wireless_design_workflow_manager:
        dnac_host: "{{ dnac_host }}"
        dnac_username: "{{ dnac_username }}"
        dnac_password: "{{ dnac_password }}"
        dnac_verify: "{{ dnac_verify }}"
        dnac_port: "{{ dnac_port }}"
        dnac_version: "{{ dnac_version }}"
        dnac_debug: "{{ dnac_debug }}"
        dnac_log: true
        dnac_log_level: DEBUG
        config_verify: true
        dnac_api_task_timeout: 1000
        dnac_task_poll_interval: 1
        state: deleted
        config:
          - feature_template_config:
              - rrm_general_configuration:
                  - design_name: "rrm_general_5ghz_default"
                    feature_attributes:
                      radio_band: "5GHZ"                           # enum: 2_4GHZ, 5GHZ, 6GHZ
                      monitoring_channels: "MONITORING_CHANNELS_DCA"   # enum: MONITORING_CHANNELS_ALL, MONITORING_CHANNELS_COUNTRY, MONITORING_CHANNELS_DCA
                      neighbor_discover_type: "NEIGHBOR_DISCOVER_TYPE_TRANSPARENT"  # enum: NEIGHBOR_DISCOVER_TYPE_TRANSPARENT, NEIGHBOR_DISCOVER_TYPE_PROTECTED
                      throughput_threshold: 3000                  # 1000..10000000
                      coverage_hole_detection: true
                    unlocked_attributes:
                      - "monitoring_channels"
                      - "neighbor_discover_type"
                      - "throughput_threshold"
                      - "coverage_hole_detection"

          # - design_name: "rrm_general_6ghz_high_thr"
          #   feature_attributes:
          #     radio_band: "6GHZ"
          #     monitoring_channels: "MONITORING_CHANNELS_ALL"
          #     neighbor_discover_type: "NEIGHBOR_DISCOVER_TYPE_PROTECTED"
          #     throughput_threshold: 2500000
          #     coverage_hole_detection: false
          #   unlocked_attributes:
          #     - "throughput_threshold"

          # # 2.4 GHz example (note controller support requirement per your spec)
          # - design_name: "rrm_general_24ghz_country_scope"
          #   feature_attributes:
          #     radio_band: "2_4GHZ"                          # supported only on IOS-XE >= 17.9.1
          #     monitoring_channels: "MONITORING_CHANNELS_COUNTRY"
          #     neighbor_discover_type: "NEIGHBOR_DISCOVER_TYPE_TRANSPARENT"
          #     throughput_threshold: 150000
          #     coverage_hole_detection: true
          #   unlocked_attributes:
          #     - "monitoring_channels"
          #     - "coverage_hole_detection"
